services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tasktown
    ports:
      - "5432:5432"
    volumes:
      - tasktown_pg:/var/lib/postgresql/data
volumes:
  tasktown_pg:
